import type { BrandIconProps } from '@brand-icons/core';
import {
  AFFiNELatestIcon,
  AmazonLatestIcon,
  AppleLatestIcon,
  AtlassianLatestIcon,
  AWSLatestIcon,
  AzureLatestIcon,
  BitbucketLatestIcon,
  BraveLatestIcon,
  ClaudeCodeLatestIcon,
  ClaudeLatestIcon,
  CodexLatestIcon,
  CursorLatestIcon,
  DiscordLatestIcon,
  DisneyLatestIcon,
  FacebookLatestIcon,
  FirefoxLatestIcon,
  GeminiCLILatestIcon,
  GeminiLatestIcon,
  GitHubLatestIcon,
  GitLabLatestIcon,
  GmailLatestIcon,
  GoogleCalendarLatestIcon,
  GoogleChatLatestIcon,
  GoogleChromeLatestIcon,
  GoogleCloudLatestIcon,
  GoogleDriveLatestIcon,
  GoogleLatestIcon,
  GoogleSlidesLatestIcon,
  GoogleSheetsLatestIcon,
  JetBrainsLatestIcon,
  JiraLatestIcon,
  LinearLatestIcon,
  LinkedInLatestIcon,
  MetaLatestIcon,
  MicrosoftEdgeLatestIcon,
  MicrosoftLatestIcon,
  NetflixLatestIcon,
  NotionLatestIcon,
  OpenAILatestIcon,
  SafariLatestIcon,
  SnapchatLatestIcon,
  SoraLatestIcon,
  TelegramLatestIcon,
  TwitterXLatestIcon,
  VisualStudioLatestIcon,
  VSCodeInsidersLatestIcon,
  VSCodeLatestIcon,
  YouTubeLatestIcon,
} from '@brand-icons/react';
import type { ComponentType } from 'react';

export type BrandIconComponent = ComponentType<BrandIconProps>;

export const latestIconBySlug: Readonly<Record<string, BrandIconComponent>> = {
  affine: AFFiNELatestIcon,
  amazon: AmazonLatestIcon,
  apple: AppleLatestIcon,
  atlassian: AtlassianLatestIcon,
  aws: AWSLatestIcon,
  azure: AzureLatestIcon,
  bitbucket: BitbucketLatestIcon,
  brave: BraveLatestIcon,
  chrome: GoogleChromeLatestIcon,
  claude: ClaudeLatestIcon,
  'claude-code': ClaudeCodeLatestIcon,
  codex: CodexLatestIcon,
  cursor: CursorLatestIcon,
  discord: DiscordLatestIcon,
  'disney-plus': DisneyLatestIcon,
  edge: MicrosoftEdgeLatestIcon,
  facebook: FacebookLatestIcon,
  firefox: FirefoxLatestIcon,
  gemini: GeminiLatestIcon,
  'gemini-cli': GeminiCLILatestIcon,
  github: GitHubLatestIcon,
  gitlab: GitLabLatestIcon,
  gmail: GmailLatestIcon,
  google: GoogleLatestIcon,
  'google-calendar': GoogleCalendarLatestIcon,
  'google-chat': GoogleChatLatestIcon,
  'google-cloud': GoogleCloudLatestIcon,
  'google-drive': GoogleDriveLatestIcon,
  'google-slides': GoogleSlidesLatestIcon,
  'google-sheets': GoogleSheetsLatestIcon,
  jetbrains: JetBrainsLatestIcon,
  jira: JiraLatestIcon,
  linear: LinearLatestIcon,
  linkedin: LinkedInLatestIcon,
  meta: MetaLatestIcon,
  microsoft: MicrosoftLatestIcon,
  netflix: NetflixLatestIcon,
  notion: NotionLatestIcon,
  openai: OpenAILatestIcon,
  safari: SafariLatestIcon,
  snapchat: SnapchatLatestIcon,
  sora: SoraLatestIcon,
  telegram: TelegramLatestIcon,
  twitter: TwitterXLatestIcon,
  'visual-studio': VisualStudioLatestIcon,
  vscode: VSCodeLatestIcon,
  'vscode-insiders': VSCodeInsidersLatestIcon,
  youtube: YouTubeLatestIcon,
};
