import type { BrandIconProps } from '@brand-icons/core';
import * as BrandIcons from '@brand-icons/react';
import type { ComponentType } from 'react';

export type BrandIconComponent = ComponentType<BrandIconProps>;

export const latestIconBySlug: Readonly<Record<string, BrandIconComponent>> = {
  affine: BrandIcons.AFFiNELatestIcon,
  amazon: BrandIcons.AmazonLatestIcon,
  apple: BrandIcons.AppleLatestIcon,
  arc: BrandIcons.ArcLatestIcon,
  atlassian: BrandIcons.AtlassianLatestIcon,
  aws: BrandIcons.AWSLatestIcon,
  azure: BrandIcons.AzureLatestIcon,
  bitbucket: BrandIcons.BitbucketLatestIcon,
  brave: BrandIcons.BraveLatestIcon,
  chrome: BrandIcons.GoogleChromeLatestIcon,
  claude: BrandIcons.ClaudeLatestIcon,
  'claude-code': BrandIcons.ClaudeCodeLatestIcon,
  codex: BrandIcons.CodexLatestIcon,
  cursor: BrandIcons.CursorLatestIcon,
  dashlane: BrandIcons.DashlaneLatestIcon,
  deezer: BrandIcons.DeezerLatestIcon,
  discord: BrandIcons.DiscordLatestIcon,
  'disney-plus': BrandIcons.DisneyLatestIcon,
  edge: BrandIcons.MicrosoftEdgeLatestIcon,
  facebook: BrandIcons.FacebookLatestIcon,
  figma: BrandIcons.FigmaLatestIcon,
  firefox: BrandIcons.FirefoxLatestIcon,
  gemini: BrandIcons.GeminiLatestIcon,
  'gemini-cli': BrandIcons.GeminiCLILatestIcon,
  github: BrandIcons.GitHubLatestIcon,
  gitlab: BrandIcons.GitLabLatestIcon,
  gmail: BrandIcons.GmailLatestIcon,
  google: BrandIcons.GoogleLatestIcon,
  'google-calendar': BrandIcons.GoogleCalendarLatestIcon,
  'google-chat': BrandIcons.GoogleChatLatestIcon,
  'google-cloud': BrandIcons.GoogleCloudLatestIcon,
  'google-contacts': BrandIcons.GoogleContactsLatestIcon,
  'google-docs': BrandIcons.GoogleDocsLatestIcon,
  'google-drive': BrandIcons.GoogleDriveLatestIcon,
  'google-forms': BrandIcons.GoogleFormsLatestIcon,
  'google-jamboard': BrandIcons.GoogleJamboardLatestIcon,
  'google-keep': BrandIcons.GoogleKeepLatestIcon,
  'google-meet': BrandIcons.GoogleMeetLatestIcon,
  'google-sheets': BrandIcons.GoogleSheetsLatestIcon,
  'google-sites': BrandIcons.GoogleSitesLatestIcon,
  'google-slides': BrandIcons.GoogleSlidesLatestIcon,
  'google-tasks': BrandIcons.GoogleTasksLatestIcon,
  'google-vids': BrandIcons.GoogleVidsLatestIcon,
  'google-voice': BrandIcons.GoogleVoiceLatestIcon,
  jetbrains: BrandIcons.JetBrainsLatestIcon,
  jira: BrandIcons.JiraLatestIcon,
  linear: BrandIcons.LinearLatestIcon,
  linkedin: BrandIcons.LinkedInLatestIcon,
  meta: BrandIcons.MetaLatestIcon,
  microsoft: BrandIcons.MicrosoftLatestIcon,
  netflix: BrandIcons.NetflixLatestIcon,
  notion: BrandIcons.NotionLatestIcon,
  openai: BrandIcons.OpenAILatestIcon,
  safari: BrandIcons.SafariLatestIcon,
  snapchat: BrandIcons.SnapchatLatestIcon,
  soundcloud: BrandIcons.SoundCloudLatestIcon,
  sora: BrandIcons.SoraLatestIcon,
  spotify: BrandIcons.SpotifyLatestIcon,
  telegram: BrandIcons.TelegramLatestIcon,
  twitter: BrandIcons.TwitterXLatestIcon,
  'visual-studio': BrandIcons.VisualStudioLatestIcon,
  vscode: BrandIcons.VSCodeLatestIcon,
  'vscode-insiders': BrandIcons.VSCodeInsidersLatestIcon,
  waze: BrandIcons.WazeLatestIcon,
  youtube: BrandIcons.YouTubeLatestIcon,
  'youtube-kids': BrandIcons.YouTubeKidsLatestIcon,
  'youtube-shorts': BrandIcons.YouTubeShortsLatestIcon,
  'youtube-studio': BrandIcons.YouTubeStudioLatestIcon,
};
